# For more info on HTTP files go to https://aka.ms/vs/httpfile

POST https://localhost:7033/api/auth/register
Content-Type: application/json
Accept-Charset: utf-8

{
  "email": "joao.silva@example.com",
  "password": "SenhaVálida123"
}
###
POST https://localhost:7033/api/auth/login
Content-Type: application/json
Accept-Charset: utf-8

{
  "email": "joao.silva@example.com",
  "password": "SenhaVálida123"
}

###
POST https://localhost:7033/api/locations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImU2YjhlMTA5LTI4MGMtNDY0Ni1hM2YxLTIwNmQ4MjdjZjYwOSIsImVtYWlsIjoiam9hby5zaWx2YUBleGFtcGxlLmNvbSIsIm5iZiI6MTY5NzkxNDgxMywiZXhwIjoxNjk4MzQ2ODEzLCJpYXQiOjE2OTc5MTQ4MTMsImlzcyI6IkJhbHRhaW8uRmlyc3RDaGFsbGVuZ2UiLCJhdWQiOiJCYWx0YWlvLkZpcnN0Q2hhbGxlbmdlIn0.78Ddf5hUoCrmrPMIq3Tzq1SsPV5vX_NVPKBcvHHWO50

###
GET https://localhost:7033/api/locations/9245fe4a-d402-451c-b9ed-9c1a04247482
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImU2YjhlMTA5LTI4MGMtNDY0Ni1hM2YxLTIwNmQ4MjdjZjYwOSIsImVtYWlsIjoiam9hby5zaWx2YUBleGFtcGxlLmNvbSIsIm5iZiI6MTY5NzkxNDgxMywiZXhwIjoxNjk4MzQ2ODEzLCJpYXQiOjE2OTc5MTQ4MTMsImlzcyI6IkJhbHRhaW8uRmlyc3RDaGFsbGVuZ2UiLCJhdWQiOiJCYWx0YWlvLkZpcnN0Q2hhbGxlbmdlIn0.78Ddf5hUoCrmrPMIq3Tzq1SsPV5vX_NVPKBcvHHWO50

###
PUT https://localhost:7033/api/locations/9245fe4a-d402-451c-b9ed-9c1a04247482
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImU2YjhlMTA5LTI4MGMtNDY0Ni1hM2YxLTIwNmQ4MjdjZjYwOSIsImVtYWlsIjoiam9hby5zaWx2YUBleGFtcGxlLmNvbSIsIm5iZiI6MTY5NzkxNDgxMywiZXhwIjoxNjk4MzQ2ODEzLCJpYXQiOjE2OTc5MTQ4MTMsImlzcyI6IkJhbHRhaW8uRmlyc3RDaGFsbGVuZ2UiLCJhdWQiOiJCYWx0YWlvLkZpcnN0Q2hhbGxlbmdlIn0.78Ddf5hUoCrmrPMIq3Tzq1SsPV5vX_NVPKBcvHHWO50
###
DELETE https://localhost:7033/api/locations/9245fe4a-d402-451c-b9ed-9c1a04247482
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImU2YjhlMTA5LTI4MGMtNDY0Ni1hM2YxLTIwNmQ4MjdjZjYwOSIsImVtYWlsIjoiam9hby5zaWx2YUBleGFtcGxlLmNvbSIsIm5iZiI6MTY5NzkxNDgxMywiZXhwIjoxNjk4MzQ2ODEzLCJpYXQiOjE2OTc5MTQ4MTMsImlzcyI6IkJhbHRhaW8uRmlyc3RDaGFsbGVuZ2UiLCJhdWQiOiJCYWx0YWlvLkZpcnN0Q2hhbGxlbmdlIn0.78Ddf5hUoCrmrPMIq3Tzq1SsPV5vX_NVPKBcvHHWO50
###
GET https://localhost:7033/api/locations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImU2YjhlMTA5LTI4MGMtNDY0Ni1hM2YxLTIwNmQ4MjdjZjYwOSIsImVtYWlsIjoiam9hby5zaWx2YUBleGFtcGxlLmNvbSIsIm5iZiI6MTY5NzkxNDgxMywiZXhwIjoxNjk4MzQ2ODEzLCJpYXQiOjE2OTc5MTQ4MTMsImlzcyI6IkJhbHRhaW8uRmlyc3RDaGFsbGVuZ2UiLCJhdWQiOiJCYWx0YWlvLkZpcnN0Q2hhbGxlbmdlIn0.78Ddf5hUoCrmrPMIq3Tzq1SsPV5vX_NVPKBcvHHWO50
###
POST https://localhost:7033/api/locations/import-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImU2YjhlMTA5LTI4MGMtNDY0Ni1hM2YxLTIwNmQ4MjdjZjYwOSIsImVtYWlsIjoiam9hby5zaWx2YUBleGFtcGxlLmNvbSIsIm5iZiI6MTY5NzkxNDgxMywiZXhwIjoxNjk4MzQ2ODEzLCJpYXQiOjE2OTc5MTQ4MTMsImlzcyI6IkJhbHRhaW8uRmlyc3RDaGFsbGVuZ2UiLCJhdWQiOiJCYWx0YWlvLkZpcnN0Q2hhbGxlbmdlIn0.78Ddf5hUoCrmrPMIq3Tzq1SsPV5vX_NVPKBcvHHWO50
